const userType = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
  SIGN_IN_WITH_GOOGLE :'SIGN_IN_WITH_GOOGLE',
  SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS'
}
export default userType;