const userType = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
  SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS',
  SIGN_IN_WIH_GOOGLE_SUCCESS : 'SIGN_IN_WIH_GOOGLE_SUCCESS',
}
export default userType;